"""edited realties

Revision ID: c7c7843c2c01
Revises: 
Create Date: 2020-04-17 17:37:36.370318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c7843c2c01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('realties')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('surname', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('is_realtor', sa.BOOLEAN(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=True),
    sa.Column('sort', sa.VARCHAR(), nullable=True),
    sa.CheckConstraint('is_realtor IN (0, 1)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('realties',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('photo', sa.VARCHAR(), nullable=True),
    sa.Column('realtor', sa.INTEGER(), nullable=True),
    sa.Column('house', sa.VARCHAR(), nullable=True),
    sa.Column('not_solded_flats', sa.INTEGER(), nullable=True),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.Column('cost', sa.INTEGER(), nullable=True),
    sa.Column('is_sold', sa.BOOLEAN(), nullable=True),
    sa.Column('desc', sa.INTEGER(), nullable=True),
    sa.CheckConstraint('is_sold IN (0, 1)'),
    sa.ForeignKeyConstraint(['realtor'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
